### ISSUE TITLE
When using kdiff3, --auto should not be used / should be user configurable

### ISSUE THREAD

**Issue by WildPenquin** [5long/p3wm#21]
Hi,

I can see kdiff3 uses `--auto` per default. This causes kdiff3 only to present a summary dialog, but it will not actually show the merging window at all.

This can be a preferred behavior for many users, but in my case:

1. I'm paranoid and would like to see what is going on, and the viewer options are not nice enough to see the chances. 
2. The automatic resolving is not good enough, it makes mistakes.

This should be a preference, referenced in the documentation and mentioned how to change the default behavior. Currently, the only option is to edit the script of p3wm itself. User also needs to find out what is going on, so at least a mention on the different tools would be welcome in the documentation.

Also, for example, using meld, it does show the merge even if no conflicts were found. So it seems what p3wm is also being inconsistent, at least from a users point of view (although I can see that maybe meld does not have a similar feature, hence the difference in behavior?).

**Comment by 5long** [comment]
> This can be a preferred behavior for many users

This is actually me being too lazy to test out the behaviour of kdiff3.

When a user chooses to launch a resolve tool, p3wm is supposed to run it in interactive editing mode.

It seems that removing `--auto` from the `kdiff3` command is what we want. I'll release a bugfix soon.

**Comment by 5long** [comment]
Fixed in commit bb31d39 and released 0.7.1 to AUR.

Would you please confirm that it works as expected now?
