### ISSUE TITLE
Feature Request: Non-interactive mode

### ISSUE THREAD

**Issue by BrainDamage** [5long/p3wm#8]
Thanks to 3-way merge "smartness", most of the times the changes can be auto-merged without user interaction.
For those cases ( eg find /etc -name '*.pacnew' -exec p3wm {} \; ) a non-interactive mode which attempts to auto-merge and simply quits if the changes conflict; the user can always re-run the tool manually to resolve conflicts.
I would add it myself, but I am unsure how to toggle it for the user, so I am opening this ticket for discussion; I thought of 3 ways:

- Dedicated environment variable ( eg. P3WM_AUTO_MERGE=1 )
- Re-pourpose P3WM_CMD_MERGE environment variable; since the interactive merge tool is useless for non-interactive mode, it could accept a specific value eg 'auto-only' to skip interactive mode
- Break the paradigm of single single input parameter and add a flag like -n for non-interactive mode

Personally I think 1st option would be best, but I defer to your judgement since it's your project.
In the cases of 1st or 3rd implementation also, merge command existance should be omitted since it's only necessary for interactive merge.

**Comment by 5long** [comment]
Big thanks for the feature suggestion and the PR.
